### ISSUE TITLE
Error on order.create

### ISSUE THREAD

**Issue by wali0710** [mollie/mollie-api-node#131] opened 2020-03-03 10:45 UTC
This is the error that I get when I try to create order and getCheckoutUrl()
It does not enter the promise after creating order, goes straight to the catch block. Display this error
```
TypeError: Cannot read property 'data' of undefined
    at Function.createApiError (c:\xampp\htdocs\one-day-dev\node_modules\@mollie\api-client\dist\mollie.cjs.js:1153:61)
    at c:\xampp\htdocs\one-day-dev\node_modules\@mollie\api-client\dist\mollie.cjs.js:1226:18
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (c:\xampp\htdocs\one-day-dev\node_modules\@mollie\api-client\dist\mollie.cjs.js:19:24)
    at _throw (c:\xampp\htdocs\one-day-dev\node_modules\@mollie\api-client\dist\mollie.cjs.js:45:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Pimm** [comment] 2020-03-03 11:39
Hi!

Could you share the relevant code which causes this error, please?

**Comment by wali0710** [comment] 2020-03-04 05:41
@Pimm , Thanks for replying
`
mollieClient.orders.create({
        amount: {
          value: amount,
          currency: currencyCode,
        },
        billingAddress,
        orderNumber: reference, // billing == shipping
        lines,
        metadata: {
          orderReference: reference,
        },
        redirectUrl: `https:/mysite/thank-you?orderReference=${reference}`,
        webhookUrl: `https://mysite/orders/webhook/${reference}`,
        locale: 'en_US',
      })
        .then((order) => {
          const success = (n) => {
            console.log('updated order');
            console.log(n);
          }
          const error = () => {
            console.log('failed to update order');
          }
          console.log('setting order id for ' + reference + ' to ' + order.id);
          updateOrderByReference(reference, { orderId: order.id }, success, error)
            .then(() => orderCreationEmail(reference, items, shippingDetails))
            .then(() => res.redirect(order.getCheckoutUrl()));
        }).catch((error) => {
          console.log(error);
          res.status(401).send(error);
        })
`
This is the portion of code, where I use a promise following a mollieClient.orders.create

**Comment by wali0710** [comment] 2020-03-04 17:13
@Pimm your insight with be a great help indeed.

**Comment by wali0710** [comment] 2020-03-06 09:10
@Pimm  Hi
Any update?

**Comment by Pimm** [comment] 2020-03-11 12:08
I tried your code. It produces the following error for me:
`ApiError: The redirect URL is invalid`

It works as I would expect if I change the redirect URL to this (adding a second `/`):
`https://mysite/thank-you?orderReference=${reference}`

(Just a small side note, you probably [meant to use backticks](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Template_literals) around the URL `` `https://…ce=${reference}` `` instead of quotes `'https://…ce=${reference}'`.)

Is it possible that the traffic between your machine and the Mollie servers is somehow proxied? Are you able to make any calls at all (other than creating an order)?

**Comment by wali0710** [comment] 2020-03-11 12:14
I am using backticks now, but the error remains the same.

**Comment by wali0710** [comment] 2020-03-11 12:15
The redirect URL is optional in mollie, I don't know how it still throws an error.

**Comment by wali0710** [comment] 2020-03-11 12:16
And I fixed the second `/` part as well, no good

**Comment by ndijkstra** [comment] 2020-03-11 12:33
`redirectUrl` is only optional when it is a recurring payment.

**Comment by Pimm** [comment] 2020-03-11 13:45
Sorry, I shouldn't have brought up the URL at all, as it is clearly not the source of your problem.

Is it possible that the traffic between your machine and the Mollie servers is somehow proxied? Are you able to make any calls at all (other than creating an order)?

**Comment by vernondegoede** [comment] 2020-03-11 14:41
@Pimm I think something's wrong in the module, as line `1153` contains the `createApiError` method:

```

  static createApiError(responseOrMessage, cb) {
    // This method is essentially a thin wrapper around either the ApiError constructor or ApiError.createFromResponse.
    // When we implement a more generic solution for the callbacks, I think this method becomes obsolete.
    let error;

    if (typeof responseOrMessage == 'string') {
      error = new ApiError(responseOrMessage);
    } else {
      // if (typeof responseOrMessage == 'object')
      error = ApiError.createFromResponse(responseOrMessage.data);
    }

    if (cb) {
      cb(error);
    }

    throw error;
  }
```

@Pimm Can you take a look at this line? https://github.com/mollie/mollie-api-node/blob/master/src/resource.ts#L92

**Comment by Pimm** [comment] 2020-03-11 17:10
Our error handling is currently not perfect.

However, I can't reproduce the issue @wali0710 is having at all. Can you, @vernondegoede?

**Comment by vernondegoede** [comment] 2020-03-11 17:33
I think the following could be happening:

1. `Order.create` is called, which actually delegates to `Resource.create`.
2. An API error occurs. This can be anything, and depends on the website profile of the organization. An example could be "payment method is not enabled for this account".
3. The `Resource.createApiError` method is called, however it's not a string. It's probably a v2 API error, which is an object that looks like this: https://docs.mollie.com/guides/handling-errors#id6

In our integration tests we are currently only testing the happy paths, not the error paths. Maybe that's why this hasn't been caught yet.

@Pimm could you maybe add a test case to the orders integration test that tests what happens in case of an error? I could look into it myself, but I'm currently very limited in my time.

An actual error that might be returned from the API would be:

```
{
    "status": 422,
    "title": "Unprocessable Entity",
    "detail": "The amount of the order does not match the total amount from the order lines. Expected order amount to be €1,027.99 but got €100.00",
    "field": "amount",
    "_links": {
        "documentation": {
            "href": "https://docs.mollie.com/guides/handling-errors",
            "type": "text/html"
        }
    }
}
```

**Comment by Pimm** [comment] 2020-03-12 09:29
I agree 100%, Vernon. We should invest in proper error handling.

Yet, this is not the source of the problem @wali0710 is having. I suspect he is having a network issue, but I can't be sure.

**Comment by wali0710** [comment] 2020-03-13 07:12
Hi @Pimm I have checked, my network traffic is not proxied.
It was working few days back, not it's not.

**Comment by cgduncan7** [comment] 2020-03-13 18:44
Hey guys, below is the exact object that `orders.create` is being called with.
```javascript
{
  "amount": {
    "value": "186.95",
    "currency": "EUR"
  },
  "billingAddress": {
    "streetAndNumber": "Street 1",
    "city": "City",
    "postalCode": "1234 AB",
    "country": "NL",
    "givenName": "Collin",
    "familyName": "Duncan",
    "email": "cgduncan7@gmail.com"
  },
  "orderNumber": "42480595-3391-4bf1-a199-6ea00d2523cf",
  "lines": [
    {
      "type": "physical",
      "name": "Product Name",
      "quantity": 1,
      "unitPrice": {
        "currency": "EUR",
        "value": "179.00"
      },
      "totalAmount": {
        "currency": "EUR",
        "value": "179.00"
      },
      "vatRate": "0",
      "vatAmount": {
        "currency": "EUR",
        "value": "0.00"
      },
      "metadata": {
        "itemAttributes": {
          "type": "productType",
          "material": "productMaterial",
          "date": {
            "year": 1999,
            "month": 9,
            "day": 19
          }
        }
      }
    },
    {
      "type": "shipping_fee",
      "name": "Shipping Fee",
      "quantity": 1,
      "unitPrice": {
        "currency": "EUR",
        "value": "7.95"
      },
      "totalAmount": {
        "currency": "EUR",
        "value": "7.95"
      },
      "vatRate": "0",
      "vatAmount": {
        "currency": "EUR",
        "value": "0.00"
      }
    }
  ],
  "metadata": {
    "orderReference": "42480595-3391-4bf1-a199-6ea00d2523cf"
  },
  "redirectUrl": "https://www.website.com/thank-you?orderReference=42480595-3391-4bf1-a199-6ea00d2523cf",
  "webhookUrl": "https://www.website.com/orders/webhook/42480595-3391-4bf1-a199-6ea00d2523cf",
  "locale": "en_US"
}
```

We have also added a call to `mollieClient.orders.page()` and we can successfully retrieve orders via this API. So, I am not sure that a connection issue is what is causing this.

To make matters even more strange, I was successfully able to place *1 order* today but after trying to create another it reverted back to the same error. When the order was marked as paid, all webhooks fired successfully and I was redirected back to `redirectUrl`.

I have also tried with the exact same data but to no avail.

**Comment by wali0710** [comment] 2020-03-14 07:54
@cgduncan7 explained it well, and that's the issue I am facing as well. If there was any proxy based network blocking, it should not process the first time as well. and if there is any Error Thrown by the API, than the `data` variable should have something to it. But it has nothing and we cannot debug it.

**Comment by vernondegoede** [comment] 2020-03-14 12:08
@wali0710 @cgduncan7 Can you reach out to vernon@mollie.com and share your Mollie organization ID via email?

**Comment by mcvzon** [comment] 2020-03-14 14:47
Hi there, I'm facing the same kind of error:
TypeError: Cannot read property 'data' of undefined at Function.createApiError

**Comment by mcvzon** [comment] 2020-03-14 14:56
Hi There, I'm facing the same kind of error with mollieClient.payments.create:
TypeError: Cannot read property 'data' of undefined at Function.createApiError
mollieClient seems to contain undefined data.
Did you find a solution for this issue?

**Comment by tlosbar** [comment] 2020-04-20 17:00
I have the same issue with mollieClient.payments.create...
Still no solution ?

**Comment by mcvzon** [comment] 2020-04-20 17:25
I just use fetch(mollie api) now and that works fine.

**Comment by tlosbar** [comment] 2020-04-21 08:12
In fact, the mollie client seems to work well in test mode in local (I use firebase functions and so emulators functions when I want to debug in local). 
But when the server code goes in production, the same test mode throws the error  « Cannot read property 'data' of undefined. »

Like you said here, it's hard to debug and know what is wrong :/. Maybe we have to have already a valid profile in Mollie Dashboard...

@mcvzon , thanks I'll test the mollie API directly.

**Comment by Pimm** [comment] 2020-04-21 08:14
We have a PR which should at the very least cause better errors to be thrown.

I will let you know when it has been merged.

**Comment by tlosbar** [comment] 2020-04-21 08:19
@Pimm Nice!

**Comment by mcvzon** [comment] 2020-04-21 08:25
Do you have a billing account in for firebase? Otherwise you can't make
external calls. The other reason might be the way you parse your response.
When i parsed it like you would normally parse json like request['id'] i
got undefined. When i logged the object i got undefined but when i did
request.body['id'] the data is there.
But i'm still in testing mode btw.

Op di 21 apr. 2020 om 10:13 schreef Thomas L. <notifications@github.com>:

**Comment by Pimm** [comment] 2020-04-21 09:17
@mcvzon Thanks for your efforts!

If you are playing detective, you could try using a3eb70b4902dd1a6eb98fdf974d701fc4e3d669b (instead of master). The Git repository contains the source code but not `/dist`, so you would have to `yarn build` it yourself.

**Comment by Pimm** [comment] 2020-05-19 09:20
Thank you guys so far!

If you are still experiencing this issue, could you try this with the latest beta version?

`npm install @mollie/api-client@beta`

At the very least, this should produce a more helpful error message.

**Comment by Pimm** [comment] 2020-08-19 12:25
There has been no activity for four months. A new version has been released since, which should produce more descriptive errors. If anyone is still experiencing difficulties, please create a new issue.

**Closed by Pimm** 2020-08-19 12:25 UTC
